### ISSUE TITLE
Не удается установить cs-cart multivendor

### ISSUE THREAD

**Issue by azabroflovski** [cscart/development-docker#11]
# Вступление
Не удается установить **cs-cart multivendor** на dev окружение, ничего не помогает, изучил документацию и cs-cart (как его поднять) и доки данного окружения. 

Во время установки, прогрессбар с сообщением **"Обработка"** и таком состоянии застывает, минут 20 точно ждал.

> OS: Windows 10 x64 with WSL2

![image](https://user-images.githubusercontent.com/33807338/133726136-3d1de48e-e55c-4d12-ba50-1ececdacb268.png)

<details>
  <summary>docker-compose.yml</summary>

  ```YML
  version: "3.1"
  services:
  
    mysql5.7:
      image: mysql:5.7
      container_name: mysql5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./app/db:/var/lib/mysql
      ports:
        - "3306:3306"
  
    nginx:
      image: nginx:alpine
      container_name: nginx
      working_dir: /etc/nginx
      volumes:
        - ./app:/app
        - ./config/nginx:/etc/nginx/conf.d
      ports:
        - "80:80"
        - "443:443"
      depends_on:
  #      - php5.6
  #      - php7.3
        - php7.4
  #      - php8.0
  
  #  php5.6:
  #    build:
  #      context: ./config/php5.6
  #      dockerfile: Dockerfile
  #    container_name: php5.6
  #    working_dir: /app
  #    volumes:
  #      - ./app:/app
  #      - ./config/php5.6/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
  #      - ./bin/sendmail:/usr/local/bin/sendmail
  #
  #  php7.3:
  #    build:
  #      context: ./config/php7.3
  #      dockerfile: Dockerfile
  #    container_name: php7.3
  #    working_dir: /app
  #    volumes:
  #      - ./app:/app
  #      - ./config/php7.3/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
  #      - ./bin/sendmail:/usr/local/bin/sendmail
  #    environment:
  #        PHP_IDE_CONFIG: serverName=localhost
  
    php7.4:
      build:
        context: ./config/php7.4
        dockerfile: Dockerfile
      container_name: php7.4
      working_dir: /app
      volumes:
        - ./app:/app
        - ./config/php7.4/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
        - ./bin/sendmail:/usr/local/bin/sendmail
      environment:
          PHP_IDE_CONFIG: serverName=localhost
  
  #  php8.0:
  #    build:
  #      context: ./config/php8.0
  #      dockerfile: Dockerfile
  #    container_name: php8.0
  #    working_dir: /app
  #    volumes:
  #      - ./app:/app
  #      - ./config/php8.0/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
  #      - ./bin/sendmail:/usr/local/bin/sendmail
  #    environment:
  #        PHP_IDE_CONFIG: serverName=localhost
  
  ```
</details>

## UPD
Ради эксперимента, попробовал поднять обычный cs-cart (без мултьтивендора), он ставится без проблем. Получается проблема конкретно в multi-vendor версии. Пока не понимаю из за чего это может быть.

## UPD 2
Вопрос с тормозами решил. Докер на винде, используется wsl2, я попробовал обратно на hyper-v перейти, всё чотко работает. Гораздо быстрее. Вопрос закрыт.
